'use client';

import {
    AlertCircle,
    ArrowLeft,
    BarChart2,
    Bell,
    Bold,
    Bot,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleHelp,
    Clock,
    Copy,
    Code,
    CreditCard,
    Crown,
    Cpu,
    Database,
    Diamond,
    Download,
    FileText,
    Film,
    Gift,
    Globe,
    Heart,
    History,
    Hourglass,
    Image,
    Italic,
    LayoutDashboard,
    Loader2,
    LogOut,
    Mail,
    Megaphone,
    Menu,
    MoreVertical,
    Paperclip,
    Pencil,
    Plus,
    Rocket,
    Search,
    Send,
    Settings,
    ShoppingCart,
    SlidersHorizontal,
    Smile,
    Sparkles,
    Star,
    Tag,
    Trash2,
    Upload,
    Users,
    UserPlus,
    Video,
    Check,
    X,
    Zap,
    type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

const ICON_MAP: Record<string, LucideIcon> = {
    dashboard: LayoutDashboard,
    description: FileText,
    mail: Mail,
    payments: CreditCard,
    history: History,
    settings: Settings,
    menu: Menu,
    notifications: Bell,
    close: X,
    more_vert: MoreVertical,
    send: Send,
    logout: LogOut,
    smart_toy: Bot,
    arrow_back: ArrowLeft,
    add: Plus,
    expand_more: ChevronDown,
    edit: Pencil,
    delete: Trash2,
    search: Search,
    tune: SlidersHorizontal,
    upload_file: Upload,
    download: Download,
    error: AlertCircle,
    movie: Film,
    hourglass_empty: Hourglass,
    chevron_left: ChevronLeft,
    chevron_right: ChevronRight,
    edit_note: Pencil,
    format_bold: Bold,
    format_italic: Italic,
    code: Code,
    image: Image,
    videocam: Video,
    mood: Smile,
    attach_file: Paperclip,
    rocket_launch: Rocket,
    autorenew: Loader2,
    progress_activity: Loader2,
    groups: Users,
    person_add: UserPlus,
    schedule: Clock,
    group: Users,
    auto_awesome: Sparkles,
    bar_chart: BarChart2,
    lan: Globe,
    report: FileText,
    memory: Cpu,
    database: Database,
    sell: Tag,
    shopping_cart: ShoppingCart,
    workspace_premium: Crown,
    loyalty: Heart,
    campaign: Megaphone,
    diamond: Diamond,
    star: Star,
    bolt: Zap,
    favorite: Heart,
    redeem: Gift,
    card_giftcard: Gift,
    local_offer: Tag,
    content_copy: Copy,
    check: Check,
};

export interface IconProps {
    name: string;
    className?: string;
    size?: number;
}

export function Icon({ name, className, size = 24 }: IconProps) {
    const LucideIcon = ICON_MAP[name] ?? CircleHelp;
    return (
        <LucideIcon
            className={cn('shrink-0', className)}
            size={size}
            aria-hidden
        />
    );
}
